### PR TITLE
Package structure updates

### PR DESCRIPTION
**Pull request by chacalle**
## Describe changes

@krpaulson Haidong and I want to switch to using the [`demogsurv` package](https://github.com/mrc-ide/demogsurv) that Jeff Eaton started to calculate different demographic indicators from microdata. This is our fork of that repository and eventually we'll probably try to send PRs to the upstream repo.

Small package structure changes:

* Add [Rproj](https://r-pkgs.org/workflows101.html#projects)
* Switch to github actions for continuous integration as recommended [here](https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/). Included both the package checks and pkgdown actions
  * `usethis::use_github_action(name = "check-standard")`
  * `usethis::use_github_action(name = "pkgdown")`

### CODE REVIEW

**Review by krpaulson — APPROVED** [review]
Sounds good. To what extent do we want to adhere to our best practices vs style currently existing in this package?

**Comment by chacalle** [comment]
> Sounds good. To what extent do we want to adhere to our best practices vs style currently existing in this package?

At least for the stuff I've been working on so far, I have been trying not to make too many structure/style changes so that it is easier to initially merge changes to the upstream repo.

**Comment by chacalle** [comment]
I think the checks are partially failing right now because it depends on downloading data using `rdhs` which requires a dhs username and password. Will need to see how they did this previously with travis and see if still needed given the other example data included in the package. https://github.com/ropensci/rdhs

**Comment by chacalle** [comment]
Closing in favor of https://github.com/ihmeuw-demographics/demogsurv/pull/3

**Pull request closed without merging**
